version: "3"
services:
  api:
    image: node:14.3.0-stretch
    container_name: api
    # command: ["node", "app.js"]
    command: /bin/bash -c "cd server && npm i -g pm2 && pm2-runtime start ecosystem.config.js"
    environment:
      - NODE_ENV=production
    ports:
      - "8585:8080"
    restart: always
    volumes:
      - ./:/server

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: eqx@123@xyz
    volumes:
      - ../datavolume:/var/lib/mysql

  db_admin:
    image: adminer
    restart: always
    ports:
      - 8888:8080